# Generated by Django 4.2.16 on 2024-11-01 21:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CryptosModel',
            new_name='Cryptos',
        ),
        migrations.RenameModel(
            old_name='WalletModel',
            new_name='Wallet',
        ),
    ]
