# Generated by Django 4.2.16 on 2024-11-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_cryptosmodel_cryptos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptos',
            name='acronym',
            field=models.CharField(max_length=10),
        ),
    ]
