# Generated by Django 4.2.16 on 2024-11-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_cryptos_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='current_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
