# Generated by Django 4.2.16 on 2024-11-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptos',
            name='current_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
