# Generated by Django 4.2.16 on 2024-11-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_cryptos_current_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptos',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='current_value',
        ),
        migrations.CreateModel(
            name='CryptosValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crypto_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_crypto', to='wallet.cryptos')),
            ],
        ),
    ]
