# Generated by Django 4.2.16 on 2024-11-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_cryptos_current_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptos',
            name='current_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='current_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
