# Generated by Django 4.2.16 on 2024-11-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_cryptos_current_value_wallet_current_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptos',
            old_name='name',
            new_name='crypto_name',
        ),
    ]
