# Generated by Django 4.2.16 on 2024-11-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_rename_name_cryptos_crypto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptos',
            name='current_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptosvalue',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='current_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
